### ISSUE TITLE
Destroy doesn't work

### ISSUE THREAD

**Issue by balawton** [jackmoore/zoom#101] opened 2016-02-09 04:52 UTC
When I run the 

`$('#example').trigger('zoom.destroy');`

on any element e.g.:

`$('#button').click('zoom.destroy');`

I get the following error:

Uncaught TypeError: ((jQuery.event.special[handleObj.origType] || (intermediate value)).handle || handleObj.handler).apply is not a function(…)

**Comment by jackmoore** [comment] 2016-02-09 06:52
Sorry, I couldn't reproduce this.  Can you provide more information (a demo would better)?  Can you reproduce this in an isolated way?

**Comment by balawton** [comment] 2016-02-09 07:29
Thanks for coming back to me so quick! If you run the destroy in the console on say, one of the H3s down the side of the page on your site with the demo at the link below:

Link: http://www.jacklmoore.com/zoom/
Console: $('h3').click('zoom.destroy');

You should get the error when you click on one of the H3s  e.g. 'Github Repos'. Unless I've misunderstood the selector in which case apologies!

I'm using Chrome Version 48.0.2564.103 (64-bit).

Thanks

**Comment by jackmoore** [comment] 2016-02-09 07:41
Using Chrome 48 on OSX, followed your steps and was unable to reproduce the issue.  

It's a suspicious error because I'm not using event delegation for the destroy event.  The elements that zoom was assigned to don't contain any h3 elements, it seems unlikely that calling `$('h3').click('zoom.destroy')` would invoke any of zoom's code.  Do you allow your browser addons to run in incognito mode?  If not, could you try it again in incognito mode to eliminate the possibility that you have an addon that's injecting faulty script into the page?  I'm a bit at a loss to explain the discrepancy.

**Comment by balawton** [comment] 2016-02-09 07:51
Sure, I have tried the same in Incognito and disabled all extensions in settings and I still get the error. I've attached a screenshot of what I'm trying to do - that might be easier for you to point out whether it's an issue or me being stupid...

If all seems legit can you send me something to run in the console and I'll show you the result if I still don't get any luck?

![screen shot 2016-02-09 at 14 48 34](https://cloud.githubusercontent.com/assets/6553147/12910338/89927f94-cf3c-11e5-9eef-704225ec6198.png)

**Comment by jackmoore** [comment] 2016-02-09 07:51
Oh, I see what you are doing now.  I was just thinking that the instruction `$(selector).click('string')` is nonsense, but that it shouldn't cause any errors.  I wasn't quite sure how jQuery would handle it, but I figured that since a string isn't a valid handler jQuery wouldn't try to apply it as such... but it does.

That's how you are getting an `.apply is not a function` error.  This is just a misunderstanding about the use of jQuery's click method, and unrelated to zoom.

**Comment by jackmoore** [comment] 2016-02-09 07:53
To trigger an event, use jQuery's trigger method.

What you are doing is assigning a click event with an non-valid event handler.  For me, this didn't trigger any error on assignment, but did once I clicked on something.

**Closed** 2016-02-09 07:54 UTC

**Comment by balawton** [comment] 2016-02-09 07:59
Gotcha - my bad. Thanks for going through that and for being so prompt!
